### ISSUE TITLE
Add validation on crossbar "cb_queues" for "ring_all" strategy

### ISSUE THREAD

**Issue by irfanrifai** [kazoo-community/kazoo-acdc#37]
I'm have compile the source code and found the strategy all rings haven't been added on validation cb_queues.erl

Maybe someone would like to add that validation method to this repository. My logs attached below when im trying to add the ring_all startegy via cb_queues API

```
cb_context:956(<0.5083.0>) validation errors but not strictly validating, trying to fix request
22:59:12.392 [debug] |d1c466605f5dc52f742bed3f54ded961|cb_context:971(<0.5083.0>) validation failed queues: [{data_invalid,{[{<<"default">>,<<"round_robin">>},{<<"description">>,<<"The queue strategy for connecting agents to callers">>},{<<"enum">>,[<<"round_robin">>,<<"most_idle">>]},{<<"type">>,<<"string">>}]},not_in_enum,<<"ring_all">>,[<<"strategy">>]}]
22:59:12.393 [debug] |d1c466605f5dc52f742bed3f54ded961|cb_modules_util:200(<0.5083.0>) flat token cost of 1 configured
```
I think this error is due to validation in cb_queues.erl file line 256 on fuction **is_valid_mode**

`-spec is_valid_mode(cb_context:context(), kz_json:object()) ->
          'true' |
          {'false', cb_context:context()}.
is_valid_mode(Context, Data) ->
    Mode = kz_json:get_value(<<"mode">>, Data, <<"listen">>),
    case kapi_resource:is_valid_mode(Mode) of
        'true' -> 'true';
        'false' ->
            {'false'
            ,cb_context:add_validation_error(<<"mode">>
                                            ,<<"enum">>
                                            ,kz_json:from_list(
                                               [{<<"message">>, <<"Value not found in enumerated list of values">>}
                                               ,{<<"cause">>, Mode}
                                               ])
                                            ,Context
                                            )
            }
    end.
`
Stay safe, thanks

**Comment by danielfinke** [comment]
@irfanrifai this will have to be fixed in `crossbar` as it manages the schemas for the various apps. This is just legacy behaviour from 4.3 and below. I will see about getting the schema updated to accept `"ring_all"`.

**Comment by jamesaimonetti** [comment]
@danielfinke going forward, we'll want to add to all apps' `.app.src` file (or maybe tooling should assume true unless false):

`{env,[{is_kazoo_app,true},{schemas_to_priv,true}]}`

This will start to keep schemas local to their apps. Swagger/OAS/whatever else will then be built by finding and merging these files. Will think about a public place to fetch them from vs continuing to keep them in source control.

@bradfordben FYI ^

Happy to hear thoughts on solving this if you all have ideas as well.

**Comment by danielfinke** [comment]
@jamesaimonetti I like the flag for whether schemas are local or in `crossbar`. I think the default when that is supported should be that they are app-local though. It seems like it should be pretty rare that there is even a reason to keep them in `crossbar` after that point. Maybe we don't even _need_ the flag then. Breaking change of course.

I personally like keeping the schemas in source control because it ensures (like docs) that they are revisioned in tandem with the changes to the Erlang source and don't become stale/mismatched.

Keep us updated on when the local schema support is available and I will make the changes needed here.

**Comment by danielfinke** [comment]
@irfanrifai the change has been made to the schemas and should be included in the next version of the 5.0 `crossbar` package

**Comment by jamesaimonetti** [comment]
@danielfinke to clarify, the flag exists now and works (its how we keep private apps' schemas from getting into crossbar/swagger. If unset, the flag defaults to putting in crossbar.)

Long term (and probably starting in 5.1) I'll flip it to default to the local app's priv/ dir instead.

For swagger/OAS, I would prefer to generate them on demand from whatever schemas can be found in your local repo (including open source/community/private apps). So swagger/OAS files would be locally generated and not tracked in the crossbar repo. We can provide a public location where the most recent versions of those files, generated from open source schemas, are available to those that don't want to necessarily checkout the repos needed.

So the individual schemas will remain in source control; the generated swagger/oas files would not be (is my proposal).

**Comment by danielfinke** [comment]
@jamesaimonetti OK, I gotcha. Makes sense to me to remove the swagger/OAS files as they are redundant. 👍🏻

I will look into moving the schemas into this repo
